# Array Operations



### Arithmetic Operation


In [2]:
import numpy as np

In [3]:
a1=np.arange(1,6)
a2=np.arange(6,11)


In [8]:
a1


array([1, 2, 3, 4, 5])

In [9]:
a2

array([ 6,  7,  8,  9, 10])

In [10]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [11]:
a2-a1

array([5, 5, 5, 5, 5])

### Brodcasting


### Deepp and Shallow copy


In [14]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice=a[:5]
slice=slice *10
slice

array([10, 20, 30, 40, 50])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a[4:6]*10
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operations


In [22]:
a=np.array([[1,2], [3,4]])
b=np.array([[5,6], [7,8]])

In [23]:
a*b

array([[ 5, 12],
       [21, 32]])

In [24]:
a @ b

array([[19, 22],
       [43, 50]])

In [25]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [26]:
a.T

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation


### Stacking Array


In [29]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [31]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [36]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [41]:
np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]