In [4]:
import numpy as np

### Basic Array Operation

In [6]:
arr=np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [11]:
a=[1,2,3.3,4,"hello"]
a

[1, 2, 3.3, 4, 'hello']

In [12]:
np.array(a)

array(['1', '2', '3.3', '4', 'hello'], dtype='<U32')

In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [22]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [24]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
arr=np.linspace(0,1,50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

### Random Generation Function

In [30]:
np.random.rand(10)

array([0.83289421, 0.40274929, 0.47564346, 0.94238232, 0.71879176,
       0.01684088, 0.46704626, 0.80507093, 0.89718138, 0.48764318])

In [34]:
np.random.randint(10,20,5)

array([14, 10, 16, 10, 16])

### Array Attributes

In [5]:
arr=np.array([[1,2,3],[4,5,6],[8,9,5]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 5]])

In [6]:
arr.shape


(3, 3)

In [7]:
arr.size

9

In [8]:
arr.dtype

dtype('int32')

### Array Methods

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 5]])

In [10]:
arr.min()

1

In [11]:
arr.max()

9

In [12]:
arr.sum()

43

In [13]:
np.sum(arr, axis=0)

array([13, 16, 14])

In [14]:
arr.mean()

4.777777777777778

In [16]:
arr.argmin()

0

### Reshaping and Resizing

In [18]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
arr=arr.reshape(6,5)

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])