In [1]:
import numpy as np

## Numpy indexing and slicing of vectors

In [2]:
arr=np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [3]:
arr[0]

11

In [4]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30])

In [5]:
arr[2::2]

array([13, 15, 17, 19, 21, 23, 25, 27, 29])

## Numpy indexing and slicing of matrix

In [6]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [13]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

## Boolean Indexing

In [14]:
arr=np.arange(1, 11)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_index= arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [20]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])